# Generated by Django 5.0.4 on 2026-04-28 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference_schedule', '0001_initial'),
        ('talks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='talk',
            field=models.ForeignKey(blank=True, help_text="Select a Talk if it's a Speaker giving a talk", null=True, on_delete=django.db.models.deletion.CASCADE, to='talks.proposal'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['start_time', 'end_time'], name='conference__start_t_b7a0c6_idx'),
        ),
    ]
