# Generated by Django 5.0.4 on 2026-04-28 18:56

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_alter_eventyear_id_alter_pyconevent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(default='', max_length=200)),
                ('page_title', models.CharField(default='', max_length=200)),
                ('meta_og_image', models.ImageField(blank=True, default='meta-image.png', help_text='Upload your cover image or leave blank to use our default image', null=True, upload_to='ticket_page')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('font_icon_code', models.CharField(default='fa-brands fa-python', help_text='The font icon for the page, use the following format - fa-brands fa-python', max_length=200)),
                ('content', markdownx.models.MarkdownxField(default='', help_text='[Supports Markdown] - Content for the page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_year', models.ForeignKey(default='2025', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='home.eventyear')),
            ],
        ),
    ]
