E = {"title": "", "speaker": ""}


SCHEDULE_DATA = [
    {
        "id": "day1",
        "label": "Wed, Oct 7 — Workshops & PyData Summit",
        "rooms": ["Victoria Ball Room", "Majestic Hall", "Royal Hall", "Regal Hall"],
        "slots": [
            {"time": "9:00 – 11:00", "cells": [
                E,
                {"title": "The Essence of Data Visualisation: Mapping from Data to Visual Properties", "speaker": "Hassah Kibirige"},
                {"title": "PyData Summit", "speaker": ""},
                {"title": "Sponsor Workshops", "speaker": ""},
            ]},
            {"time": "10:30 – 11:00", "span": True, "title": "Break", "type": "break"},
            {"time": "11:00 – 13:00", "cells": [
                E,
                {"title": "GDE Workshop", "speaker": ""},
                {"title": "PyData Summit", "speaker": ""},
                {"title": "Sponsor Workshops", "speaker": ""},
            ]},
            {"time": "13:00 – 14:00", "span": True, "title": "Lunch", "type": "break"},
            {"time": "14:00 – 16:00", "cells": [
                E,
                {"title": "Computer Vision in 10 Lines of Code: Rapid Prototyping with FastAI", "speaker": "Victor Olufemi"},
                {"title": "PyData Summit", "speaker": ""},
                {"title": "Sponsor Workshops", "speaker": ""},
            ]},
            {"time": "16:00 – 18:00", "cells": [
                E,
                {"title": "Building Your First RESTful API", "speaker": "Anthony Addae"},
                {"title": "PyData Summit", "speaker": ""},
                {"title": "Sponsor Workshops", "speaker": ""},
            ]},
        ],
    },
    {
        "id": "day2",
        "label": "Thu, Oct 8 — Workshops & WiDs",
        "rooms": ["Victoria Ball Room", "Majestic Hall", "Royal Hall", "Regal Hall"],
        "slots": [
            {"time": "9:00 – 11:00", "cells": [
                E,
                {"title": "Demystifying Robotics & IoT with MicroPython", "speaker": "Zenas Awuku"},
                {"title": "Humble Data workshop", "speaker": "Cecilia Tivir"},
                {"title": "WiDs", "speaker": ""},
            ]},
            {"time": "10:30 – 11:00", "span": True, "title": "Break", "type": "break"},
            {"time": "11:00 – 13:00", "cells": [
                E,
                {"title": "LLMs Expert Session", "speaker": "GDEs"},
                {"title": "Securing Django 6.0 Apps with Built-in Content Security Policy", "speaker": "Kiringabakwe Ibrahim"},
                {"title": "WiDs", "speaker": ""},
            ]},
            {"time": "13:00 – 14:00", "span": True, "title": "Lunch", "type": "break"},
            {"time": "14:00 – 16:00", "cells": [
                E,
                {"title": "Hands-On: Building an AI Agent with Python to Detect Risky Customers", "speaker": "Hussein Kizza"},
                {"title": "Building Pearl-Chat: Overcoming the Technical Challenges of Architecting a Native Luganda LLM in Pure JAX", "speaker": "Wesley Kambale"},
                {"title": "WiDs", "speaker": ""},
            ]},
            {"time": "16:00 – 18:00", "cells": [
                E,
                {"title": "SQLAlchemy: the Swiss Army Knife of Databases for Python", "speaker": "ZOKORA ELVIS GBAGNON"},
                {"title": "CPython Internals", "speaker": "Lincoln Angufibo"},
                E,
            ]},
        ],
    },
    {
        "id": "day3",
        "label": "Fri, Oct 9 — Conference Day 1",
        "rooms": [
            "Victoria Ball Room - AI/ML",
            "Majestic Hall - AI/Agentic",
            "Royal Hall - Web/Security",
            "Regal Hall - Core",
        ],
        "slots": [
            {"time": "7:00 – 8:45", "span": True, "title": "Break Tea", "type": "break"},
            {"time": "9:00 – 9:15", "span": True, "title": "Opening Remarks"},
            {"time": "9:15 – 10:15", "span": True, "title": "Opening Keynote"},
            {"time": "10:20 – 11:05", "cells": [
                {"title": "Automating Hardware Diagnostics: Resurrecting Motherboards with Python and a Raspberry Pi", "speaker": "Collins Mesue"},
                {"title": "MLOPs with MLFLow (A Value Estimation Example)", "speaker": "Ronald Matovu"},
                {"title": "Pyladies Africa", "speaker": ""},
                {"title": "Community Summit", "speaker": ""},
            ]},
            {"time": "11:10 – 11:55", "cells": [
                {"title": "Getting started with mechanistic interpretability", "speaker": "Rashid Kisejjere"},
                {"title": "GenAI Inside: Embedding AI into Enterprise Workflows with Python", "speaker": "Muhammad Aliyu"},
                {"title": "Pyladies Africa", "speaker": ""},
                {"title": "Community Summit", "speaker": ""},
            ]},
            {"time": "12:00 – 12:45", "cells": [
                {"title": "CPython Under Load: NoGIL, Green Threads, AsyncIO vs Other Langs — Deep-Dive and Benchmarks", "speaker": "Petr Andreev"},
                {"title": "Mastering Deep Learning: One Python Script at a Time", "speaker": "Charles Moruri"},
                {"title": "Pyladies Africa", "speaker": ""},
                {"title": "Community Summit", "speaker": ""},
            ]},
            {"time": "12:50 – 13:00", "span": True, "title": "Sponsor Plenary Talk"},
            {"time": "13:00 – 14:00", "span": True, "title": "Lunch", "type": "break"},
            {"time": "14:05 – 14:50", "cells": [
                {"title": "Turning Food into Medicine with Local LLMs: The Future of Chronic Disease Management", "speaker": "Daniel Samuel Etukudo"},
                {"title": "From Hospital Records to REST API: Training and Serving XGBoost Disease Prediction Models in Python", "speaker": "Ernest Essien"},
                {"title": "Pyladies Africa", "speaker": ""},
                {"title": "Community Summit", "speaker": ""},
            ]},
            {"time": "14:55 – 15:40", "cells": [
                {"title": "The Mathematical Representation of Vision: From Linear Algebra to Deepfake Detection", "speaker": "Mark Lubega"},
                {"title": "From Zero to GPU: Serverless ML Inference on a Budget with Modal and Python", "speaker": "Arnold Ighiwiyisi"},
                {"title": "Pyladies Africa", "speaker": ""},
                {"title": "Community Summit", "speaker": ""},
            ]},
            {"time": "15:50 – 16:50", "span": True, "title": "Closing Keynote"},
            {"time": "16:50 – 17:20", "span": True, "title": "Lightning Talks"},
        ],
    },
    {
        "id": "day4",
        "label": "Sat, Oct 10 — Conference Day 2",
        "rooms": [
            "Victoria Ball Room - core python",
            "Majestic Hall - AI/Agentic",
            "Royal Hall - Security/Web",
            "Regal Hall - Web",
            "Pavilion setup",
        ],
        "slots": [
            {"time": "7:00 – 8:45", "span": True, "title": "Break Tea", "type": "break"},
            {"time": "9:00 – 9:15", "span": True, "title": "Opening Remarks"},
            {"time": "9:15 – 10:15", "span": True, "title": "Opening Keynote"},
            {"time": "10:20 – 11:05", "cells": [
                {"title": "Let the Computer Run Your Unit Tests: Property-Based Testing with Hypothesis in Python", "speaker": "Batamye Umar Isabirye"},
                {"title": "Building Real-Time Voice Agents That Listen and Respond in Python", "speaker": "Glory Bagai"},
                {"title": "Python in the Browser: No install, No barrier", "speaker": "Hypolit Zeuchieu"},
                {"title": "Django Girls Workshop", "speaker": ""},
                {"title": "Posters", "speaker": ""},
            ]},
            {"time": "11:10 – 11:40", "cells": [
                {"title": "Working with Audio in Python (Pythonic Approach)", "speaker": "Bashir Kasujja"},
                {"title": "Detecting Firmware Implants with Python Assisted Bare-Metal Forensics", "speaker": "Victor Ashioya"},
                {"title": "Enhancing FastMCP Server Security", "speaker": "Mugoya Hillarious"},
                {"title": "Django Girls Workshop", "speaker": ""},
                {"title": "Posters", "speaker": ""},
            ]},
            {"time": "11:45 – 12:15", "cells": [
                {"title": "Python for Microcontrollers: Introduction to MicroPython & Wokwi Simulator", "speaker": "Samuel Lunghe"},
                {"title": "Building Event-Driven Systems in Python That Survive Production", "speaker": "Abdulmateen Tairu"},
                {"title": "Python at Scale: A Practical Guide to Serving 1 Million Users with FastAPI and Flask", "speaker": "Moses Daudu"},
                {"title": "Django Girls Workshop", "speaker": ""},
                {"title": "Posters", "speaker": ""},
            ]},
            {"time": "12:20 – 13:00", "span": True, "title": "Open Source, Research and Industry Panel (Micheal Nitegeka, Richard Zulu, CK Japheth and Grace Kamulegeya)"},
            {"time": "13:00 – 14:00", "span": True, "title": "Lunch", "type": "break"},
            {"time": "14:05 – 14:35", "cells": [
                {"title": "Deterministic Python: Implementing RTOS Design Concepts in MicroPython", "speaker": "Shawal Mbalire"},
                {"title": "Designing Python APIs for Data You Don't Control", "speaker": "Saurav Jain"},
                {"title": "When Step 3 Fails: Reliable Multi-Step Workflows in Celery Using the Saga Pattern", "speaker": "Douglas Amoo-Sargon"},
                {"title": "Django Girls Workshop", "speaker": ""},
                {"title": "Posters", "speaker": ""},
            ]},
            {"time": "14:40 – 15:10", "cells": [
                {"title": "Building Low-Power IoT Systems with LoRaWAN and Python", "speaker": "Job mbugua"},
                {"title": "Serving LLMs on a Budget with vLLM", "speaker": "Ifihanagbara Olusheye"},
                {"title": "Async Python and FastAPI: How It Actually Works", "speaker": "Theresa Seyram Agbenyegah"},
                {"title": "Django Girls Workshop", "speaker": ""},
                {"title": "Posters", "speaker": ""},
            ]},
            {"time": "15:15 – 15:45", "cells": [
                {"title": "Back to the Fixtures", "speaker": "Steve Yonkeu"},
                {"title": "Advanced Design Patterns for ML Systems", "speaker": "Victor Ashioya"},
                {"title": "Delivering with Django: Boring Tech, Real Impact in Africa's Startups", "speaker": "Bernard Katamanso"},
                {"title": "Django Girls Workshop", "speaker": ""},
                {"title": "Posters", "speaker": ""},
            ]},
            {"time": "15:50 – 16:50", "span": True, "title": "Closing Keynote"},
            {"time": "16:50 – 17:20", "span": True, "title": "Lightning Talks\nDjango Deployment Isn't What It Used to Be. by victorianyamai\nUsing Python to Automate API Testing in Open Source Projects by Christine\nSecuring Networks with Python: A Deep Dive into Intrusion Detection, Phishing Prevention, and Vulnerability Scoring by Alpha\nWhat Nobody Tells You About Running a Developer Community as a Student by adjanour\nThe Informal Economy Doesn't Have an API by John_iroko\nDesign isn't just for the Frontend: Why backend developers should care about UX. by Miriam-Birungi"},
        ],
    },
    {
        "id": "day5",
        "label": "Sun, Oct 11 — Conference Day 3",
        "rooms": [
            "Victoria Ball Room - Security/Web",
            "Majestic Hall - ML/Data science",
            "Royal Hall - AI/Agentic",
            "Regal Hall - Core",
        ],
        "slots": [
            {"time": "7:00 – 8:45", "span": True, "title": "Break Tea", "type": "break"},
            {"time": "9:00 – 9:15", "span": True, "title": "Opening Remarks"},
            {"time": "9:15 – 10:15", "span": True, "title": "Opening Keynote"},
            {"time": "10:20 – 11:05", "cells": [
                {"title": "Hacking for Good: Cybersecurity and Ethical Hacking with Python", "speaker": "Mvenyi Donald Mbutu"},
                {"title": "The Lazy Wizard's Guide to Federated Learning: Building ML Models in Difficult Places", "speaker": "Johannes Kolbe"},
                {"title": "From Single Agents to Production Teams: Building Multi-Agent Systems with Python, MCP, and Persistent Memory", "speaker": "David Agbolade"},
                {"title": "Refugee Program", "speaker": ""},
            ]},
            {"time": "11:10 – 11:40", "cells": [
                {"title": "Breaking Bad in Python: A Chaos Engineering Story", "speaker": "Joyce Dzifa Lokko"},
                {"title": "V-MATH and Veri-Math: Step Level Verification for Enhancing Mathematical Reasoning in Large Language Models", "speaker": "John Paul Rugaba Rugaba"},
                {"title": "Designing Python-First AI Programs for African Universities: A Practical Framework", "speaker": "Elvira Khwatenge"},
                {"title": "Refugee Program", "speaker": ""},
            ]},
            {"time": "11:45 – 12:15", "cells": [
                {"title": "How I Used Python to Control Kubernetes with Voice Notes on Telegram", "speaker": "Daniel Mwiine"},
                {"title": "Federated Learning as a Distributed Systems Problem: Designing Production-Grade ML Systems in Python", "speaker": "David Asem"},
                {"title": "Speech Synthesis Unpacked: Building a Voice Cloning TTS Model with Python", "speaker": "Nunsi Shiaki"},
                {"title": "Refugee Program", "speaker": ""},
            ]},
            {"time": "12:20 – 13:00", "span": True, "title": "Dedicated Expo Hall Time"},
            {"time": "13:00 – 14:00", "span": True, "title": "Lunch", "type": "break"},
            {"time": "14:05 – 14:35", "cells": [
                {"title": "Delivering with Django: Boring Tech, Real Impact in Africa's Startups", "speaker": "Bernard Katamanso"},
                {"title": "Continuous translation with Weblate in the age of AI", "speaker": "Gersona Andrianarijaona"},
                {"title": "Deploying Intelligence at the Edge: Building Real-World Perception Systems with Python on Constrained Hardware", "speaker": "Obed Honour Eje"},
                {"title": "Refugee Program", "speaker": ""},
            ]},
            {"time": "14:40 – 15:10", "cells": [
                {"title": "PaSSw0rdVib3s!: Finding Passwords in Digital Evidence", "speaker": "Anne Fleur van Luenen"},
                {"title": "Building Clinical Tools in Data-Constrained Environments: Python, ML, and the Human Spine", "speaker": "Christine Akoto-Nimoh"},
                {"title": "Cyber Security Workshop", "speaker": ""},
                {"title": "Refugee Program", "speaker": ""},
            ]},
            {"time": "15:15 – 15:45", "cells": [
                {"title": "Background Jobs at Scale: Designing Reliable Python Worker Systems", "speaker": "Efe Omoregie"},
                {"title": "Building Civic Tech with Python: APIs, Data, and Systems for Public Good", "speaker": "Alamin Magaga"},
                {"title": "Cyber Security Workshop", "speaker": ""},
                {"title": "Refugee Program", "speaker": ""},
            ]},
            {"time": "15:50 – 16:50", "span": True, "title": "Closing Keynote"},
            {"time": "16:50 – 17:20", "span": True, "title": "Lightning Talks\nYour Code is Great...but Who Knows? by sarahmuwanguzi\nPython for Impact: Building Climate Solutions Rooted in African Communities by Tendai Jack\nOpen Source Is Infrastructure. Why We Must Stop Treating It Like a Hobby by Trudy\nPython for Community Impact: Simple Tech Solutions for Refugee and Rural Communities in Africa by sankara"},
        ],
    },
]
