# Generated by Django 5.0.4 on 2026-04-28 18:56

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import django_extensions.db.fields
import hashid_field.field
import hitcount.views
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=64, verbose_name='activation key')),
                ('activated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'registration profile',
                'verbose_name_plural': 'registration profiles',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', default=None, min_length=7, prefix='', primary_key=True, serialize=False)),
                ('profile_image', models.ImageField(blank=True, default='', upload_to='speakers/')),
                ('name', models.CharField(default='', max_length=100)),
                ('surname', models.CharField(default='', max_length=100)),
                ('link_to_speaker_image', models.URLField(blank=True, default='', help_text="A link to your professional profile picture to be used when making speaker's announcements")),
                ('profession', models.CharField(default='', help_text="Speaker's profession. eg. Software Developer", max_length=200, null=True)),
                ('organization', models.CharField(blank=True, default='', help_text='Organization/Institution', max_length=200, null=True)),
                ('biography', markdownx.models.MarkdownxField(default='', help_text='[Supports Markdown] - Give us a brief biography about yourself')),
                ('city', models.CharField(default='', help_text='City the speaker is from eg. Kampala', max_length=100)),
                ('country', django_countries.fields.CountryField(default='UG', max_length=2)),
                ('contact_number', models.CharField(blank=True, default='', help_text='Please include your country code (256).', max_length=50, null=True)),
                ('website', models.URLField(blank=True, help_text='Your website/blog URL.', null=True)),
                ('twitter_handle', models.CharField(blank=True, default='', help_text="Please enter only the user name eg.'your_user_name'", max_length=100, null=True)),
                ('github_username', models.CharField(blank=True, default='', help_text="Please enter only the user name eg.'your_user_name'", max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, default='', help_text='Please your LinkedIn link', max_length=100, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('is_a_sponsor_or_keynote_speaker', models.BooleanField(default=False)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, hitcount.views.HitCountMixin),
        ),
        migrations.CreateModel(
            name='SupervisedRegistrationProfile',
            fields=[
                ('registrationprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.registrationprofile')),
            ],
            bases=('registration.registrationprofile',),
        ),
    ]
