# Generated by Django 5.0.4 on 2026-04-28 18:56

import django.contrib.auth.models
import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_alter_eventyear_id_alter_pyconevent_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Code of Conduct PyCon Uganda', max_length=250)),
                ('code_of_conduct', markdownx.models.MarkdownxField(default='', help_text='[Supports Markdown] - COC PyCon Uganda.')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('event_year', models.ForeignKey(default='2025', on_delete=django.db.models.deletion.CASCADE, related_name='cocs', to='home.eventyear')),
                ('user', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='coc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
