# Generated by Django 4.2.23 on 2025-06-25 20:42

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_aid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Financial Assistance PyCon Uganda', max_length=250)),
                ('financial_assistance', markdownx.models.MarkdownxField(default='', help_text='[Supports Markdown] - Financial Assistance PyCon Uganda.')),
                ('google_form_formfacade_code', models.TextField(blank=True, default='', help_text='Link to your google form')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('fin_open_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the financial aid form opens')),
                ('fin_close_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the financial aid form closes')),
                ('event_year', models.ForeignKey(default='2025', on_delete=django.db.models.deletion.CASCADE, related_name='fin_aids', to='home.eventyear')),
                ('user', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='fin_aid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_edit_fin_aid', 'Can edit financial aid form')],
            },
        ),
    ]
