# Generated by Django 5.0.4 on 2026-04-20 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinAidReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fin_aid_reviewer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opportunity grant reviewer',
                'verbose_name_plural': 'Opportunity grant reviewers',
            },
        ),
        migrations.CreateModel(
            name='OpportunityGrantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(help_text='Name as it should appear on correspondence.', max_length=255)),
                ('country_or_region', models.CharField(max_length=255)),
                ('support_type', models.CharField(choices=[('travel', 'Travel'), ('accommodation', 'Accommodation'), ('ticket', 'Conference ticket'), ('other', 'Other / combination')], max_length=32)),
                ('budget_narrative', models.TextField(help_text='Describe estimated costs or how funds would be used.')),
                ('why_need_support', models.TextField(help_text='Why are you applying for an opportunity grant?')),
                ('community_contribution', models.TextField(help_text='How do you contribute to the Python or broader tech community?')),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_review', 'In review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlist', 'Waitlist')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fin_aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='fin_aid.fin_aid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_grant_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opportunity grant application',
                'verbose_name_plural': 'Opportunity grant applications',
                'permissions': [('can_review_fin_aid_application', 'Can review opportunity grant applications')],
            },
        ),
        migrations.CreateModel(
            name='FinAidApplicationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(choices=[('accept', 'Accept / fund'), ('reject', 'Reject'), ('unsure', 'Unsure / needs discussion')], default='unsure', max_length=16)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_reviews', to='fin_aid.finaidreviewer')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='fin_aid.opportunitygrantapplication')),
            ],
            options={
                'verbose_name': 'Opportunity grant application review',
                'verbose_name_plural': 'Opportunity grant application reviews',
            },
        ),
        migrations.AddConstraint(
            model_name='opportunitygrantapplication',
            constraint=models.UniqueConstraint(fields=('fin_aid', 'user'), name='unique_opportunity_grant_application_per_user_round'),
        ),
        migrations.AddConstraint(
            model_name='finaidapplicationreview',
            constraint=models.UniqueConstraint(fields=('application', 'reviewer'), name='unique_fin_aid_application_review_per_reviewer'),
        ),
    ]
