# Generated by Django 5.0.4 on 2026-04-20 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0002_opportunity_grant_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fin_aid',
            name='google_form_formfacade_code',
        ),
    ]
