# Generated by Django 5.0.4 on 2026-04-20 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0003_remove_google_form_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fin_aid',
            options={'permissions': [('can_edit_fin_aid', 'Can edit financial aid form')], 'verbose_name': 'Opportunity grant configuration', 'verbose_name_plural': 'Opportunity grant configurations'},
        ),
        migrations.RemoveField(
            model_name='fin_aid',
            name='financial_assistance',
        ),
    ]
