# Generated by Django 5.0.4 on 2026-04-20 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0004_remove_financial_assistance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fin_aid',
            name='user',
        ),
    ]
