# Generated by Django 5.0.4 on 2026-06-04 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0006_opportunity_grant_country_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finaidreviewer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='finaidreviewer',
            name='review_load',
            field=models.CharField(choices=[('all', 'All — review every application'), ('equal', 'Equal — fair share via round-robin')], default='equal', max_length=16),
        ),
        migrations.CreateModel(
            name='FinAidReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='fin_aid.opportunitygrantapplication')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_aid_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fin_aid.finaidreviewer')),
            ],
            options={
                'verbose_name': 'Opportunity grant review assignment',
                'verbose_name_plural': 'Opportunity grant review assignments',
            },
        ),
        migrations.AddConstraint(
            model_name='finaidreviewassignment',
            constraint=models.UniqueConstraint(fields=('reviewer', 'application'), name='unique_fin_aid_review_assignment'),
        ),
    ]
