# Generated by Django 5.0.4 on 2026-06-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0007_reviewer_load_and_review_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaidapplicationreview',
            name='alignment_score',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Alignment score (0–5)'),
        ),
        migrations.AddField(
            model_name='finaidapplicationreview',
            name='has_disability',
            field=models.BooleanField(default=False, verbose_name='Person with disability'),
        ),
        migrations.AddField(
            model_name='finaidapplicationreview',
            name='is_local_contributor',
            field=models.BooleanField(default=False, verbose_name='Local contributor'),
        ),
        migrations.AddField(
            model_name='finaidapplicationreview',
            name='is_organizer',
            field=models.BooleanField(default=False, verbose_name='Organizer'),
        ),
        migrations.AddField(
            model_name='finaidapplicationreview',
            name='is_professional_cant_afford',
            field=models.BooleanField(default=False, verbose_name='Professional who cannot afford to attend'),
        ),
        migrations.AddField(
            model_name='finaidapplicationreview',
            name='is_speaker',
            field=models.BooleanField(default=False, verbose_name='Speaker'),
        ),
        migrations.AddField(
            model_name='finaidapplicationreview',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='finaidapplicationreview',
            name='is_woman',
            field=models.BooleanField(default=False, verbose_name='Woman'),
        ),
        migrations.AddField(
            model_name='finaidapplicationreview',
            name='region',
            field=models.CharField(blank=True, choices=[('uganda', 'Uganda'), ('east_africa', 'East Africa (not Uganda)'), ('other_africa', 'Other Africa'), ('outside_africa', 'Outside Africa')], default='', max_length=20, verbose_name='Region'),
        ),
    ]
