# Generated by Django 5.0.4 on 2026-06-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0008_scoring_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaidapplicationreview',
            name='grant_type',
            field=models.CharField(blank=True, choices=[('travel', 'Travel'), ('accommodation', 'Accommodation'), ('ticket', 'Conference ticket'), ('other', 'Other / combination')], default='', max_length=32, verbose_name='Grant type'),
        ),
    ]
