# Generated by Django 5.0.4 on 2026-06-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0009_add_grant_type_to_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaidapplicationreview',
            name='total_score',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
