# Generated by Django 5.0.4 on 2026-06-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0010_persist_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaidapplicationreview',
            name='is_motivated_student',
            field=models.BooleanField(default=False, verbose_name='Motivated student'),
        ),
        migrations.AlterField(
            model_name='finaidapplicationreview',
            name='total_score',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
