# Generated by Django 5.0.4 on 2026-06-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0011_split_student_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaidapplicationreview',
            name='recommendation',
            field=models.CharField(choices=[('accept', 'Accept / fund'), ('partial', 'Partial grant'), ('reject', 'Reject'), ('unsure', 'Unsure / needs discussion')], default='unsure', max_length=16),
        ),
    ]
