# Generated by Django 5.0.4 on 2026-06-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0012_add_partial_grant_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaidapplicationreview',
            name='amount_exceeded',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="How much the applicant's requested budget exceeds the regional flight cap, in USD.", max_digits=8, null=True, verbose_name='Amount exceeded (USD)'),
        ),
    ]
