# Generated by Django 5.0.4 on 2026-06-21 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0013_add_amount_exceeded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaidapplicationreview',
            name='amount_exceeded',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="How much the applicant's requested budget exceeds the regional flight cap, in USD.", max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount exceeded (USD)'),
        ),
        migrations.AlterField(
            model_name='opportunitygrantapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('in_review', 'In review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlist', 'Partially accepted')], default='submitted', max_length=20),
        ),
    ]
