# Generated by Django 5.0.4 on 2026-06-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0014_alter_finaidapplicationreview_amount_exceeded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitygrantapplication',
            name='user_response',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Declined')], default='P', max_length=1),
        ),
    ]
