# Generated by Django 5.0.4 on 2026-06-27 19:14

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0015_add_user_response_to_opportunitygrantapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitygrantapplication',
            name='ticket_code',
            field=models.CharField(blank=True, default='', help_text='Ticket redemption code from Quicket.', max_length=100),
        ),
        migrations.AddField(
            model_name='opportunitygrantapplication',
            name='travel_grant_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Travel support amount in USD. Leave blank for ticket-only grants.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='opportunitygrantapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('ticket_code', ''), _negated=True), fields=('ticket_code',), name='unique_nonempty_ticket_code'),
        ),
    ]
