# Generated by Django 5.0.4 on 2026-06-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0016_add_ticket_code_and_travel_grant_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalGrantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('kenya', 'Kenya'), ('rwanda', 'Rwanda'), ('tanzania', 'Tanzania'), ('south_sudan', 'South Sudan'), ('drc', 'DRC'), ('uganda', 'Uganda'), ('other', 'Other')], help_text='Country of residence', max_length=32)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], max_length=32)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('is_18', models.BooleanField(help_text='Applicant must be 18 or older', verbose_name='I confirm that I am 18 years or older')),
                ('status', models.CharField(choices=[('student', 'Student'), ('employed', 'Employed'), ('freelancer', 'Freelancer'), ('other', 'Other')], help_text='Current employment/student status', max_length=32)),
                ('field', models.CharField(help_text='Your field of study or professional field', max_length=255, verbose_name='Field of study or work')),
                ('python_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=32, verbose_name='Python proficiency level')),
                ('python_duration', models.CharField(choices=[('lt_6m', '< 6 months'), ('6_12m', '6–12 months'), ('1_2y', '1–2 years'), ('2y_plus', '2+ years')], max_length=32, verbose_name='How long have you been using Python?')),
                ('why_attend', models.TextField(help_text='Tell us about your motivation for attending', verbose_name='Why do you want to attend PyCon Africa?')),
                ('hope_to_gain', models.TextField(help_text='What skills, knowledge, or connections are you looking for?', verbose_name='What do you hope to gain from the conference?')),
                ('interests', models.CharField(help_text='e.g., AI/ML, Web Development, Data Science, Open Source, DevOps/Cloud', max_length=255, verbose_name='Areas of interest (comma-separated)')),
                ('community', models.TextField(blank=True, help_text='Optional: Tell us about your involvement in tech communities', verbose_name='Are you part of any community or organization?')),
                ('contributions', models.TextField(blank=True, help_text='Optional: Open source, mentoring, organizing events, etc.', verbose_name='How have you contributed to the tech community?')),
                ('knowledge_sharing', models.TextField(blank=True, help_text='Optional: Blogging, teaching, talks, etc.', verbose_name='How do you share knowledge with others?')),
                ('attend_all', models.BooleanField(help_text='Confirm your commitment to attend the full conference', verbose_name='I can attend all days of the conference')),
                ('represent_professionally', models.BooleanField(help_text='Agree to represent the event and community professionally', verbose_name='I will represent the regional grant program professionally')),
                ('share_publicly', models.BooleanField(help_text='Permission to share your experience on social media, etc.', verbose_name='I agree to share my experience publicly')),
                ('represent_how', models.CharField(blank=True, help_text='Optional: Social media, blog posts, presentations, etc.', max_length=255, verbose_name='How will you represent the event?')),
                ('has_national_id', models.BooleanField(default=False, help_text='Confirm you have a national ID', verbose_name='I have a valid national ID')),
                ('has_passport', models.BooleanField(default=False, help_text='Confirm you have a valid passport', verbose_name='I have a valid passport')),
                ('can_travel', models.BooleanField(default=False, help_text='Confirm you can get travel documents for attending', verbose_name='I can obtain travel documents if needed')),
                ('can_cover_expenses_with_ticket', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='e.g. accommodation, food, and other personal costs', max_length=8, verbose_name='If given a to-and-return bus ticket to the event, would you be able to cover all your other expenses?')),
                ('can_attend_with_travel_support', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Let us know if travel support alone would enable you to attend', max_length=8, verbose_name='Would you be able to get a conference ticket if given travel support?')),
                ('financial_support', models.CharField(choices=[('travel', 'Travel'), ('accommodation', 'Accommodation'), ('conference_ticket', 'Conference Ticket'), ('none', 'None')], help_text='Select the type of support you may need', max_length=32, verbose_name='Do you need financial support?')),
                ('additional_notes', models.TextField(blank=True, help_text='Optional: Additional information about yourself', verbose_name='Additional notes')),
                ('application_status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regional grant application',
                'verbose_name_plural': 'Regional grant applications',
            },
        ),
    ]
