# Generated by Django 5.0.4 on 2026-07-22 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0017_regionalgrantapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalgrantapplication',
            name='country',
            field=models.CharField(choices=[('kenya', 'Kenya'), ('rwanda', 'Rwanda'), ('tanzania', 'Tanzania'), ('south_sudan', 'South Sudan'), ('other', 'Other')], help_text='Country of residence', max_length=32),
        ),
        migrations.CreateModel(
            name='RegionalGrantApplicationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(choices=[('accept', 'Accept / fund'), ('partial', 'Partial grant'), ('reject', 'Reject'), ('unsure', 'Unsure / needs discussion')], default='unsure', max_length=16)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_community_member', models.BooleanField(default=False, verbose_name='Active in a tech community')),
                ('is_active_contributor', models.BooleanField(default=False, verbose_name='Contributes to the tech community')),
                ('is_knowledge_sharer', models.BooleanField(default=False, verbose_name='Shares knowledge with others')),
                ('python_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='', max_length=32, verbose_name='Python proficiency level (confirm/override)')),
                ('python_duration', models.CharField(blank=True, choices=[('lt_6m', '< 6 months'), ('6_12m', '6–12 months'), ('1_2y', '1–2 years'), ('2y_plus', '2+ years')], default='', max_length=32, verbose_name='Python experience duration (confirm/override)')),
                ('financial_need', models.CharField(blank=True, choices=[('travel', 'Travel'), ('accommodation', 'Accommodation'), ('conference_ticket', 'Conference Ticket'), ('none', 'None')], default='', max_length=32, verbose_name='Financial need (confirm/override)')),
                ('is_woman', models.BooleanField(default=False, verbose_name='Woman')),
                ('has_disability', models.BooleanField(default=False, verbose_name='Person with disability')),
                ('is_student', models.BooleanField(default=False, verbose_name='Student')),
                ('alignment_score', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Alignment score (0–5)')),
                ('total_score', models.FloatField(default=0, editable=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='fin_aid.regionalgrantapplication')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_grant_application_reviews', to='fin_aid.finaidreviewer')),
            ],
            options={
                'verbose_name': 'Regional grant application review',
                'verbose_name_plural': 'Regional grant application reviews',
            },
        ),
        migrations.CreateModel(
            name='RegionalGrantCountryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('kenya', 'Kenya'), ('rwanda', 'Rwanda'), ('tanzania', 'Tanzania'), ('south_sudan', 'South Sudan'), ('other', 'Other')], max_length=32)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regional_grant_country_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_country_assignments', to='fin_aid.finaidreviewer')),
            ],
            options={
                'verbose_name': 'Regional grant country assignment',
                'verbose_name_plural': 'Regional grant country assignments',
            },
        ),
        migrations.AddConstraint(
            model_name='regionalgrantapplicationreview',
            constraint=models.UniqueConstraint(fields=('application', 'reviewer'), name='unique_regional_grant_application_review_per_reviewer'),
        ),
        migrations.AddConstraint(
            model_name='regionalgrantcountryassignment',
            constraint=models.UniqueConstraint(fields=('reviewer', 'country'), name='unique_regional_grant_country_assignment'),
        ),
    ]
