# Generated by Django 5.0.4 on 2026-07-22 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0018_regional_grant_review_process'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalgrantapplicationreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_grant_application_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='regionalgrantcountryassignment',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_country_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
