# Generated by Django 5.0.4 on 2026-08-03 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0019_regional_grant_reviewer_any_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalGrantReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='fin_aid.regionalgrantapplication')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regional_grant_review_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_grant_review_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regional grant review assignment',
                'verbose_name_plural': 'Regional grant review assignments',
            },
        ),
        migrations.AddConstraint(
            model_name='regionalgrantreviewassignment',
            constraint=models.UniqueConstraint(fields=('reviewer', 'application'), name='unique_regional_grant_review_assignment'),
        ),
    ]
