# Generated by Django 5.0.4 on 2026-08-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0020_regionalgrantreviewassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalgrantapplication',
            name='proof_of_ticket',
            field=models.FileField(blank=True, help_text='Proof of PyCon Africa conference ticket registration (PDF or image).', null=True, upload_to='regional_grant_proofs/'),
        ),
        migrations.AddField(
            model_name='regionalgrantapplication',
            name='user_response',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Declined')], default='P', max_length=1),
        ),
    ]
