# Generated by Django 5.0.4 on 2026-08-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0021_regionalgrantapplication_proof_of_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalgrantapplication',
            name='status_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the accept/reject notification email for the current status was last sent successfully.', null=True),
        ),
    ]
