# Generated by Django 5.0.4 on 2026-08-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0022_regionalgrantapplication_status_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitygrantapplication',
            name='status_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the accept/reject notification email for the current status was last sent successfully.', null=True),
        ),
    ]
