# Generated by Django 5.0.4 on 2026-04-28 18:56

import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_alter_eventyear_id_alter_pyconevent_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sponsorship Tier name. eg, Gold, Silver', max_length=100)),
                ('amount', models.IntegerField(help_text='Sponsorship Tier Amount eg, 1000.00')),
                ('colour', models.CharField(default='primary', help_text='Colour for tier eg, yellow, gray, primary etc', max_length=25)),
                ('hex', models.CharField(default='#000', help_text='Hex colour for tier eg, #cd7f32', max_length=25)),
                ('details', markdownx.models.MarkdownxField(help_text='[Supports Markdown] - Detailed description of the tier.')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which the tier should be displayed.')),
                ('show_in_grid', models.BooleanField(default=False, help_text='Tick this if the sponsors in this tier should be displayed in a grid layout.')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('event_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship_tiers', to='home.eventyear')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship_tier_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorshipBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', markdownx.models.MarkdownxField(default='', help_text='[Supports Markdown] - Full Benefit in .md')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='sponsor_us.sponsorshiptier')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.TextField(blank=True)),
                ('sponsorship_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_resources', to='sponsor_us.sponsorshiptier')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Support PyCon Uganda', max_length=250)),
                ('why_sponsor_us', markdownx.models.MarkdownxField(help_text='[Supports Markdown] - Support PyCon Uganda.')),
                ('special_sponsorship', markdownx.models.MarkdownxField(help_text='[Supports Markdown] - Special sponsorship package.')),
                ('prospectus_link', models.URLField(blank=True, help_text='Link to the sponsorship prospectus.')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('event_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportus_pages', to='home.eventyear')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportus_pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
