# Generated by Django 5.0.4 on 2026-04-28 18:56

import django.contrib.auth.models
import django.db.models.deletion
import django_countries.fields
import embed_video.fields
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_alter_eventyear_id_alter_pyconevent_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(help_text='About PyCon Uganda', max_length=250)),
                ('about_tagline', models.CharField(blank=True, help_text='Tagline for the year', max_length=250)),
                ('about_image_one', models.ImageField(help_text='Upload your cover image or leave blank to use our default image', upload_to='about_page')),
                ('section_one_title', models.CharField(blank=True, default='WHAT IS | PyCon Uganda?', help_text='About PyCon Uganda', max_length=250)),
                ('section_one', markdownx.models.MarkdownxField(default='', help_text='[Supports Markdown] - About PyCon Uganda.')),
                ('section_two_title', models.CharField(blank=True, default='THE | PROGRAM', help_text='About PyCon Uganda', max_length=250)),
                ('section_two', markdownx.models.MarkdownxField(default='', help_text='[Supports Markdown] - About PyCon Uganda.')),
                ('section_three_title', models.CharField(blank=True, default='THE | TEAM', help_text='About PyCon Uganda', max_length=250)),
                ('section_three', markdownx.models.MarkdownxField(default='', help_text='[Supports Markdown] - About PyCon Uganda.')),
                ('section_four', markdownx.models.MarkdownxField(blank=True, default='', help_text='[Supports Markdown] - More about PyCon Uganda.')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('event_year', models.ForeignKey(default='2025', on_delete=django.db.models.deletion.CASCADE, related_name='abouts', to='home.eventyear')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_us', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IOCGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_year', models.ForeignKey(default='2025', on_delete=django.db.models.deletion.CASCADE, related_name='ioc_groups', to='home.eventyear')),
            ],
        ),
        migrations.CreateModel(
            name='IOCMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, default='', max_length=100)),
                ('country', django_countries.fields.CountryField(default='GH', max_length=2)),
                ('country_2', models.CharField(blank=True, default='', help_text='(enter member"s 2nd contributing country if any)', max_length=50)),
                ('is_lead', models.BooleanField(default=False, help_text='Indicate if this member is a lead')),
                ('event_year', models.ForeignKey(default='2025', on_delete=django.db.models.deletion.CASCADE, related_name='ioc_members', to='home.eventyear')),
                ('groups', models.ManyToManyField(blank=True, related_name='iocs', to='about.iocgroup')),
            ],
        ),
        migrations.CreateModel(
            name='LOCGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_year', models.ForeignKey(default='2025', on_delete=django.db.models.deletion.CASCADE, related_name='loc_groups', to='home.eventyear')),
            ],
        ),
        migrations.CreateModel(
            name='LOCMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, default='', max_length=100)),
                ('country', django_countries.fields.CountryField(default='GH', max_length=2)),
                ('is_lead', models.BooleanField(default=False, help_text='Indicate if this member is a lead')),
                ('event_year', models.ForeignKey(default='2025', on_delete=django.db.models.deletion.CASCADE, related_name='loc_members', to='home.eventyear')),
                ('groups', models.ManyToManyField(blank=True, related_name='members', to='about.locgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Travel_Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Travel Advice PyCon Uganda', max_length=250)),
                ('advice', markdownx.models.MarkdownxField(default='', help_text='[Supports Markdown] - Travel Advice PyCon Uganda.')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('event_year', models.ForeignKey(default='2025', on_delete=django.db.models.deletion.CASCADE, related_name='travel_advices', to='home.eventyear')),
                ('user', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='travel_advice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_year', models.ForeignKey(default='2025', on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_groups', to='home.eventyear')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, default='', max_length=100)),
                ('event_year', models.ForeignKey(default='2025', on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='home.eventyear')),
                ('groups', models.ManyToManyField(related_name='volunteers', to='about.volunteergroup')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Venue of PyCon Uganda', max_length=250)),
                ('content', markdownx.models.MarkdownxField(default='', help_text='[Supports Markdown] - Content.')),
                ('content_two', markdownx.models.MarkdownxField(default='', help_text='[Supports Markdown] - Content side two.')),
                ('link_to_preview_video_url', embed_video.fields.EmbedVideoField(blank=True, default='', help_text='Link to Preview video on your Youtube or Google drive')),
                ('google_map', models.CharField(default='', help_text='Venue Google map ID', max_length=500)),
                ('location', models.CharField(default='', help_text='Location of Venue', max_length=250)),
                ('location_address', models.CharField(default='', help_text='Location of Venue', max_length=250)),
                ('location_website', models.URLField(blank=True, default='', help_text="Venue's website if any")),
                ('image_one', models.URLField(default='', help_text='Link to image')),
                ('image_two', models.URLField(default='', help_text='Link to image')),
                ('first_day_of_event', models.DateTimeField(blank=True, null=True)),
                ('last_day_of_event', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('event_year', models.ForeignKey(default='2025', on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='home.eventyear')),
            ],
            options={
                'verbose_name': 'venue',
                'verbose_name_plural': 'venues',
                'unique_together': {('name',)},
            },
        ),
    ]
