# Generated by Django 5.0.4 on 2026-04-28 18:56

import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_alter_eventyear_id_alter_pyconevent_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_title', models.CharField(help_text='Ticket PyCon Uganda', max_length=250, null=True)),
                ('ticket_image_one', models.ImageField(blank=True, default='tickets.png', help_text='Upload your cover image or leave blank to use our default image', null=True, upload_to='ticket_page')),
                ('section_one', markdownx.models.MarkdownxField(blank=True, default='', help_text='[Supports Markdown] - Section One.', null=True)),
                ('section_two', markdownx.models.MarkdownxField(blank=True, default='', help_text='[Supports Markdown] - Section Two', null=True)),
                ('embedded_codes', markdownx.models.MarkdownxField(blank=True, default='', help_text='[Supports Markdown] - If the Ticket Platform allows you to embed the tickets into your site.', null=True)),
                ('donation_link', models.CharField(blank=True, help_text='Donation for PyCon Uganda if any', max_length=250, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('event_year', models.ForeignKey(default='2025', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='home.eventyear')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_us', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
