# Generated by Django 5.0.4 on 2026-05-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfpsubmissionperiod',
            name='submission_type',
            field=models.CharField(choices=[('talks', 'Talks & Workshops'), ('posters', 'Posters')], default='talks', help_text='Type of submission this period covers', max_length=20),
        ),
        migrations.AddField(
            model_name='proposal',
            name='poster_attachment',
            field=models.FileField(blank=True, help_text='Upload a PDF, PPT, or image of your poster (optional but recommended).', null=True, upload_to='poster_attachments/'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='talk_type',
            field=models.CharField(choices=[('Lightning Talk', 'Lightning Talk - 5 mins'), ('Short Talk', 'Short Talk - 30 mins'), ('Long Talk', 'Long Talk - 45 mins'), ('Tutorial', 'Tutorial - 2 hours'), ('Poster', 'Poster'), ('Sponsored Talk', 'Sponsored Talk'), ('Keynote Speaker', 'Keynote Speaker')], max_length=50),
        ),
    ]
