# Generated by Django 5.0.4 on 2026-05-06 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_add_poster_type_and_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive reviewers are skipped during assignment.'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='review_load',
            field=models.CharField(choices=[('all', 'Review all proposals'), ('equal', 'Review an equal share')], default='equal', help_text="'all' = assigned every eligible proposal. 'equal' = receives a fair share alongside other equal-share reviewers.", max_length=10),
        ),
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='talks.proposal')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='talks.reviewer')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('reviewer', 'proposal')},
            },
        ),
    ]
