# Generated by Django 5.0.4 on 2026-07-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0004_proposal_last_program_status_email_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedSpeaker',
            fields=[
            ],
            options={
                'verbose_name': 'Confirmed Speaker',
                'verbose_name_plural': 'Confirmed Speakers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('talks.proposal',),
        ),
    ]
